version: "2"

linters:
  default: standard
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
  exclusions:
    rules:
      - linters:
          - errcheck
        path: _test\.go
